$HOME/.npm:NPM Cache:true
$HOME/.npm/_logs/*:NPM Logs
$HOME/.cache/yarn:Yarn Cache
$HOME/.pnpm-store:PNPM Store
$HOME/.cache/node-gyp/*:Node-gyp Cache
$HOME/.cache/pip:Python pip cache
$HOME/.local/share/virtualenvs:Python virtualenvs
$HOME/.cargo/registry/cache/*:Cargo Registry Cache
$HOME/Personal/**/target:Rust Target Folders
$HOME/.m2/repository/*:Maven Repository
$HOME/.gradle/caches/*:Gradle Cache
$HOME/go/pkg/mod/cache/*:Go Module Cache
$HOME/.vscode/extensions/.obsolete/*:VSCode Obsolete Extensions
/var/lib/snapd/cache/*:Snap Cache:true
