$HOME/.cache/thumbnails/*:Thumbnail Cache
$HOME/.cache/google-chrome:Chrome Cache
$HOME/.cache/mozilla/firefox:Firefox Cache
$HOME/.var/app/app.zen_browser.zen/cache/*:Zen Browser Cache
$HOME/.local/share/Trash/files/*:Trash Files
$HOME/.local/share/Trash/info/*:Trash Info Files
/var/cache/man/*:Man-db Cache:true
/var/lib/systemd/coredump/*:Systemd Core Dumps:true
/var/log/*.[0-9]:Rotated Logs:true
/var/log/*.gz:Rotated Logs (gzipped):true
